apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: fastapy
  name: fastapy
  namespace: default
spec:
  selector:
    matchLabels:
      app: fastapy  
  template:
    metadata:
      labels:
        app: fastapy
    spec:
      containers:
      - image: fastapy:latest
        imagePullPolicy: Never
        name: fastapy    
        ports:
        - containerPort: 9000
          name: main
          protocol: TCP        